<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RollForward>Major</RollForward>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../EndpointConfiguration.cs" Link="EndpointConfiguration.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>
</Project>
